---
- name: Configure EpicBook backend
  hosts: backend
  gather_facts: true
  vars:
    mysql_fqdn: "{{ lookup('env', 'MYSQL_FQDN') }}"
    mysql_admin_username: "{{ lookup('env', 'MYSQL_ADMIN_USERNAME') }}"
    mysql_admin_password: "{{ lookup('env', 'MYSQL_ADMIN_PASSWORD') }}"
  roles:
    - backend

- name: Configure EpicBook frontend
  hosts: frontend
  gather_facts: true
  vars:
    backend_private_ip: "{{ lookup('env', 'BACKEND_PRIVATE_IP') }}"
  roles:
    - frontend
